### ISSUE TITLE
Attempting to open decrypted save file

### ISSUE THREAD

**Issue by Avellea** [ennuo/toolkit#17]
Hi. I'm attempting to open my LBP Vita save file, decrypted by Apollo Save Manager. I see two files, `bigfart1` and `bigfart2`. Attempting to open either of them result in the following error.

```
[10:12:57] Reading file at C:\Users\Avellea\Desktop\bigfart1
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 5309 out of bounds for length 5309
	at ennuo.craftworld.serializer.Data.i8(Data.java:156)
	at ennuo.craftworld.serializer.Data.varint(Data.java:417)
	at ennuo.craftworld.serializer.Data.u32(Data.java:293)
	at ennuo.craftworld.serializer.Serializer.u32(Serializer.java:195)
	at ennuo.craftworld.resources.structs.SlotID.serialize(SlotID.java:31)
	at ennuo.craftworld.resources.structs.SlotID.serialize(SlotID.java:9)
	at ennuo.craftworld.serializer.Serializable.serialize(Serializable.java:14)
	at ennuo.craftworld.serializer.Serializer.array(Serializer.java:473)
	at ennuo.craftworld.serializer.Serializer.array(Serializer.java:451)
	at ennuo.craftworld.types.savedata.BigProfile.serialize(BigProfile.java:90)
	at ennuo.craftworld.serializer.Serializable.serialize(Serializable.java:14)
	at ennuo.craftworld.serializer.Serializer.struct(Serializer.java:419)
	at ennuo.craftworld.types.BigStreamingFart.parseProfile(BigStreamingFart.java:287)
	at ennuo.craftworld.types.BigStreamingFart.process(BigStreamingFart.java:176)
	at ennuo.craftworld.types.BigStreamingFart.<init>(BigStreamingFart.java:93)
	at ennuo.toolkit.functions.ProfileCallbacks.loadProfile(ProfileCallbacks.java:18)
	at ennuo.toolkit.functions.ProfileCallbacks.loadProfile(ProfileCallbacks.java:14)
	at ennuo.toolkit.windows.Toolkit.loadBigProfileActionPerformed(Toolkit.java:1799)
	at ennuo.toolkit.windows.Toolkit$52.actionPerformed(Toolkit.java:1293)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at com.github.weisj.darklaf.ui.menu.DarkMenuItemUIBase.doClick(DarkMenuItemUIBase.java:155)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Am I possibly doing something wrong? Does Craftworld Toolkit not support Vita saves? I'm a little confused as to what I'm supposed to do here. Any help is appreciated, thank you!

**Comment by ennuo** [comment]
The Vita support is pretty limited unfortunately. The `cwlib` branch does have more support for Vita than main, although it's still a work in progress. It also doesn't support re-saving the profiles as of yet.

**Comment by Avellea** [comment]
> The Vita support is pretty limited unfortunately. The `cwlib` branch does have more support for Vita than main, although it's still a work in progress. It also doesn't support re-saving the profiles as of yet.

Ahh, good to know. I may build that branch just to experiment. Thanks for letting me know! I'll go ahead and mark this as closed.
