### ISSUE TITLE
exporting level as a mod doesnt work

### ISSUE THREAD

**Issue by metraberryy** [ennuo/toolkit#3]
happens for hash and guid, farc and map loaded

```
[17:33:34] Waiting for user to select file...
[17:33:40] Could not extract hAD4DAC536B54708C73617A41DFA7FD316880A1BF
[17:33:40] Could not extract h386B1DC5FD9F57DD96A0A413666CB4D4AE48A5EE
[17:33:40] Could not extract hD47AF5DAD103F3FAB153C4315AF1DB134D2C4A91
[17:33:40] Could not extract h005893C4A80C2020CC29ABD1367421EA664F2294
[17:33:40] Could not extract h2F47A4F1AFEC512125E3699528C1D6B7DB5E981F
[17:33:40] Could not extract h50CBFF0D51EAED81D9FDB7ACB3DD0A9DA3EA76EB
[17:33:40] Could not extract h8DF3386B8BD953BED04DDD2E6D285CDE96AF6E40
[17:33:40] Could not extract h06EB20E20423DC99DAEC9AE41ECF570CC09F7BC7
[17:33:40] Could not extract h0A058DC27DF61459D37C174988390B10B25D177E
[17:33:40] Could not extract h8324E02769623B3088EE94B574442854E3083AFF
[17:33:40] Could not extract h1C0DB2D5917B07E480FF27A447D12D9F1BD3F3A5
[17:33:40] Could not extract hB0877341E5920748C217E1ADC3B7BC9D19AA78E1
[17:33:40] Could not extract h48D1598952BBD6DD7B59FF1B19F4DEF32AE76B7B
[17:33:40] Could not extract hB5AB5A2254E638D32D6C6EA3D6B086F1A40CFD88
[17:33:40] Could not extract h3A1C98F9D2A746D110267761FBFC913A851032C8
[17:33:40] Could not extract hD25DAD1298921D732C6EE1EC7A7DAFF8024324AA
[17:33:40] Could not extract h3C048B16A4A460C0A1990E39FA01CDF62EF0C2B8
[17:33:40] Could not extract hEA7CB5D95559BD4FA7561F952EABC44336B7F0BE
[17:33:40] Could not extract h3F6B871470F1CF8EB5A1459A746BA85E3EDA499D
[17:33:40] Could not extract h6ADC07BD4D2E3DBA6A55539DC9DB9DD78E0500EB
[17:33:40] Could not extract h0F8F7A188976A62A9598B93A433D706EC2C8141C
[17:33:40] Could not extract hB0BC4CCEFB84EF7527FC7229313A9C0826352CB8
[17:33:40] Could not extract h512DD334468D3AA125A11CFE2BB0EEB1E84C4A91
[17:33:40] Could not extract h9292367DDD55C1F3B1630F2AACC96E46D509CB78
[17:33:40] Could not extract h2E7908D50EECC9AD5F7D37404D3E1A9B1BA89617
[17:33:40] Could not extract hFA218D2444AB19EA404384440F7D1DE038DF90F9
[17:33:40] Could not extract h97A02A9A1A0FB0FDC432002B4A85A2FD4F1E31B9
[17:33:41] Could not extract h005893C4A80C2020CC29ABD1367421EA664F2294
[17:33:41] Could not extract h50CBFF0D51EAED81D9FDB7ACB3DD0A9DA3EA76EB
[17:33:41] Could not extract h06EB20E20423DC99DAEC9AE41ECF570CC09F7BC7
[17:33:41] Could not extract hB0877341E5920748C217E1ADC3B7BC9D19AA78E1
[17:33:41] Could not extract hB5AB5A2254E638D32D6C6EA3D6B086F1A40CFD88
[17:33:42] Writing file to C:\Users\Metraberryy\Documents\test.mod
```

trying to install the mod shows a mess of clearly incorrect data, or sometimes, fails to load entirely (both lbp1)

case 1
```
[17:37:47] Waiting for user to select files...
[17:37:51] Reading file at C:\Users\Metraberryy\Documents\test.mod
[17:37:51] Mod is not encrypted
[17:37:51] Mod has revison = 6, compatibility = 31 (ALL)
[17:37:51] Mod has version = 01.00
[17:37:51] Mod has author = Sackthing, title = intro_level, description = Standard mod template.
[17:37:51] Mod has 453 entries
[17:37:51] Mod has 0 inventory patches
[17:37:51] Mod has 1 slots
[17:37:51] slot has root = hAB91CA4BC80726632A8094FB6E42FB2BC1BF4197
[17:37:51] slot has adventure = g10682
[17:37:51] slot has author = 
[17:37:51] Slot has translationKey = intro
[17:37:51] Slot has title = level?ﾈ￪???ﾝﾳ???ﾘo??ﾘo???????ﾘo?ﾝﾳ?
```

case 2
```
[17:42:34] Waiting for user to select files...
[17:42:37] Reading file at C:\Users\Metraberryy\Documents\test3.mod
[17:42:37] Mod is not encrypted
[17:42:37] Mod has revison = 6, compatibility = 31 (ALL)
[17:42:37] Mod has version = 01.00
[17:42:37] Mod has author = Sackthing, title = mexico_desert_main_bandit_town, description = Standard mod template.
[17:42:37] Mod has 1072 entries
[17:42:37] Mod has 0 inventory patches
[17:42:37] Mod has 1 slots
[17:42:37] slot has root = h0378A71AE72DC59E88A4C4CB3C306E00A6339CEF
[17:42:37] slot has adventure = g10682
[17:42:37] slot has author = 
[17:42:37] Slot has translationKey = mexico_desert_m
[17:42:37] Slot has title = Unnamed Level, description = in_bandit_town?ﾈ￪???ﾝﾳ???ﾘo??ﾘo???????ﾘo?ﾝﾳ?
[17:42:37] Slot is locked? false
[17:42:37] Slot is copyable? false
[17:42:37] Slot has levelType = COOPERATIVE
[17:42:37] Slot is sublevel? true
[17:42:37] Slot has minPlayers = -27, maxPlayers = -28
[17:42:37] Slot has move support? true
[17:42:37] Slot is cross-compatible? true
[17:42:37] Slot has gameMode = NONE
[17:42:37] Slot has customBadgeSize = -6
[17:42:37] Mod has 55 file patches
Exception in thread "AWT-EventQueue-0" java.lang.Error: Unknown Patch!
	at ennuo.craftworld.patches.ModPatch.deserialize(ModPatch.java:17)
	at ennuo.craftworld.types.Mod.process(Mod.java:207)
	at ennuo.craftworld.types.Mod.<init>(Mod.java:67)
	at ennuo.toolkit.functions.ModCallbacks.loadMod(ModCallbacks.java:21)
	at ennuo.toolkit.functions.UtilityCallbacks.installMod(UtilityCallbacks.java:155)
	at ennuo.toolkit.windows.Toolkit.installProfileModActionPerformed(Toolkit.java:1733)
	at ennuo.toolkit.windows.Toolkit.access$6500(Toolkit.java:73)
	at ennuo.toolkit.windows.Toolkit$70.actionPerformed(Toolkit.java:1343)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by ennuo** [comment]
Just got back to this, the issue also happens when creating new slots in LBP1 in general, apparently the slot constructor was defaulting to planet and background decorations from a later LBP game, which causes the level to fail to load in LBP1.

**Comment by metraberryy** [comment]
just tested again, guid works perfectly but loading the hash one gives a memory access violation crash
id assume thats more a problem with the game though

**Comment by metraberryy** [comment]
i get the same memory access violation with some levels from deploy so i think its safe to say this is fixed
