### ISSUE TITLE
Can't open my Big profile.

### ISSUE THREAD

**Issue by cmyk05** [ennuo/toolkit#5]
I have an LBP1 profile copied to the USB, I open BIG000 and I get this.

[14:00:59] Waiting for user to select file...
[14:01:03] Reading file at E:\PS3\SAVEDATA\BCES00141PROFILE61C1C95A\BIG000
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Illegal Capacity: -615587866
	at java.util.ArrayList.<init>(Unknown Source)
	at ennuo.craftworld.types.BigProfile.process(BigProfile.java:118)
	at ennuo.craftworld.types.BigProfile.<init>(BigProfile.java:63)
	at ennuo.toolkit.functions.ProfileCallbacks.loadProfile(ProfileCallbacks.java:15)
	at ennuo.toolkit.windows.Toolkit.loadBigProfileActionPerformed(Toolkit.java:1578)
	at ennuo.toolkit.windows.Toolkit.access$4200(Toolkit.java:73)
	at ennuo.toolkit.windows.Toolkit$47.actionPerformed(Toolkit.java:1113)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by cmyk05** [comment]
turns out I can't open anything else either. I was viewing my .farc and .map earlier but now they juts don't work no matter the version, search stays disabled. Not corrupted because they work on farctool2.

**Comment by ennuo** [comment]
Only non-encrypted saves can be read by Toolkit, profile and level backups in the form of 0 or BIG000 are encrypted.

**Comment by ennuo** [comment]
You'll have to provide other errors for the issues with the map and FARC.

**Comment by pindvs** [comment]
you

> I have an LBP1 profile copied to the USB, I open BIG000 and I get this.
> 
> [14:00:59] Waiting for user to select file... [14:01:03] Reading file at E:\PS3\SAVEDATA\BCES00141PROFILE61C1C95A\BIG000 Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Illegal Capacity: -615587866 at java.util.ArrayList.(Unknown Source) at ennuo.craftworld.types.BigProfile.process(BigProfile.java:118) at ennuo.craftworld.types.BigProfile.(BigProfile.java:63) at ennuo.toolkit.functions.ProfileCallbacks.loadProfile(ProfileCallbacks.java:15) at ennuo.toolkit.windows.Toolkit.loadBigProfileActionPerformed(Toolkit.java:1578) at ennuo.toolkit.windows.Toolkit.access$4200(Toolkit.java:73) at ennuo.toolkit.windows.Toolkit$47.actionPerformed(Toolkit.java:1113) at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) at javax.swing.DefaultButtonModel.setPressed(Unknown Source) at javax.swing.AbstractButton.doClick(Unknown Source) at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) at java.awt.Component.processMouseEvent(Unknown Source) at javax.swing.JComponent.processMouseEvent(Unknown Source) at java.awt.Component.processEvent(Unknown Source) at java.awt.Container.processEvent(Unknown Source) at java.awt.Component.dispatchEventImpl(Unknown Source) at java.awt.Container.dispatchEventImpl(Unknown Source) at java.awt.Component.dispatchEvent(Unknown Source) at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) at java.awt.Container.dispatchEventImpl(Unknown Source) at java.awt.Window.dispatchEventImpl(Unknown Source) at java.awt.Component.dispatchEvent(Unknown Source) at java.awt.EventQueue.dispatchEventImpl(Unknown Source) at java.awt.EventQueue.access$500(Unknown Source) at java.awt.EventQueue$3.run(Unknown Source) at java.awt.EventQueue$3.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.awt.EventQueue$4.run(Unknown Source) at java.awt.EventQueue$4.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.awt.EventQueue.dispatchEvent(Unknown Source) at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) at java.awt.EventDispatchThread.pumpEvents(Unknown Source) at java.awt.EventDispatchThread.pumpEvents(Unknown Source) at java.awt.EventDispatchThread.run(Unknown Source)

you need to open bigfart file, not BIG...

**Comment by hi-code1** [comment]
> Only non-encrypted saves can be read by Toolkit, profile and level backups in the form of 0 or BIG000 are encrypted.

Then how do I un-crypt the 0 or BIG000 files
